"""add audit_log table

Revision ID: 1403231b5deb
Revises: f9bff52d1773
Create Date: 2026-05-09 13:10:00.272284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1403231b5deb'
down_revision: Union[str, Sequence[str], None] = 'f9bff52d1773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('audit_id', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=16), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=16), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('status_color', sa.String(length=16), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_module', ['module'], unique=False)
        batch_op.create_index('ix_audit_log_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_audit_log_run_at', ['run_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_run_at')
        batch_op.drop_index('ix_audit_log_project_id')
        batch_op.drop_index('ix_audit_log_module')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
