"""add incident_reports table

Revision ID: 2670783b7954
Revises: f1125584fa19
Create Date: 2026-05-09 19:29:18.560065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2670783b7954'
down_revision: Union[str, Sequence[str], None] = 'f1125584fa19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_reports',
    sa.Column('incident_id', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=16), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('affected_persons', sa.Integer(), nullable=False),
    sa.Column('date_occurred', sa.Date(), nullable=True),
    sa.Column('date_detected', sa.Date(), nullable=True),
    sa.Column('date_reported', sa.Date(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('corrective_action', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('authority_notified', sa.Boolean(), nullable=False),
    sa.Column('authority_name', sa.String(length=255), nullable=False),
    sa.Column('authority_reference', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('incident_id')
    )
    with op.batch_alter_table('incident_reports', schema=None) as batch_op:
        batch_op.create_index('ix_incident_reports_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_incident_reports_severity', ['severity'], unique=False)
        batch_op.create_index('ix_incident_reports_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_incident_reports_status')
        batch_op.drop_index('ix_incident_reports_severity')
        batch_op.drop_index('ix_incident_reports_project_id')

    op.drop_table('incident_reports')
    # ### end Alembic commands ###
