"""add oversight_plans table

Revision ID: 3a6027e32dfc
Revises: aea6f9f57c46
Create Date: 2026-05-09 19:04:50.433247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a6027e32dfc'
down_revision: Union[str, Sequence[str], None] = 'aea6f9f57c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oversight_plans',
    sa.Column('plan_id', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=16), nullable=False),
    sa.Column('operator_profile', sa.Text(), nullable=False),
    sa.Column('has_documentation', sa.String(length=8), nullable=False),
    sa.Column('automation_bias_training', sa.String(length=8), nullable=False),
    sa.Column('outputs_include_uncertainty', sa.String(length=8), nullable=False),
    sa.Column('override_mechanism', sa.String(length=8), nullable=False),
    sa.Column('override_logged', sa.String(length=8), nullable=False),
    sa.Column('stop_mechanism', sa.String(length=8), nullable=False),
    sa.Column('gaps', sa.Text(), nullable=False),
    sa.Column('mitigation_plan', sa.Text(), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('compliance_percent', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oversight_plans')
    # ### end Alembic commands ###
