"""add model_cards table

Revision ID: 72a2fe09e13f
Revises: bbf12c64c999
Create Date: 2026-05-09 21:17:04.101332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '72a2fe09e13f'
down_revision: Union[str, Sequence[str], None] = 'bbf12c64c999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_cards',
    sa.Column('card_id', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=16), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('model_owners', sa.Text(), nullable=False),
    sa.Column('license', sa.String(length=128), nullable=False),
    sa.Column('citation', sa.Text(), nullable=False),
    sa.Column('references', sa.Text(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('primary_uses', sa.Text(), nullable=False),
    sa.Column('primary_users', sa.Text(), nullable=False),
    sa.Column('out_of_scope_uses', sa.Text(), nullable=False),
    sa.Column('relevant_factors', sa.Text(), nullable=False),
    sa.Column('evaluation_factors', sa.Text(), nullable=False),
    sa.Column('performance_metrics', sa.Text(), nullable=False),
    sa.Column('decision_thresholds', sa.Text(), nullable=False),
    sa.Column('training_data', sa.Text(), nullable=False),
    sa.Column('evaluation_data', sa.Text(), nullable=False),
    sa.Column('ethical_considerations', sa.Text(), nullable=False),
    sa.Column('caveats', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_cards')
    # ### end Alembic commands ###
