"""add project_inputs table

Revision ID: 955fe0dd8cdf
Revises: 72a2fe09e13f
Create Date: 2026-05-12 13:02:44.836819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '955fe0dd8cdf'
down_revision: Union[str, Sequence[str], None] = '72a2fe09e13f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_inputs',
    sa.Column('input_id', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=16), nullable=False),
    sa.Column('slot', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('input_id'),
    sa.UniqueConstraint('project_id', 'slot', name='uq_project_input_slot')
    )
    with op.batch_alter_table('project_inputs', schema=None) as batch_op:
        batch_op.create_index('ix_project_inputs_project_id', ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_inputs', schema=None) as batch_op:
        batch_op.drop_index('ix_project_inputs_project_id')

    op.drop_table('project_inputs')
    # ### end Alembic commands ###
