"""add risk_register table

Revision ID: aea6f9f57c46
Revises: 1403231b5deb
Create Date: 2026-05-09 18:37:46.120638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aea6f9f57c46'
down_revision: Union[str, Sequence[str], None] = '1403231b5deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_register',
    sa.Column('risk_id', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('likelihood', sa.String(length=16), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('mitigation', sa.Text(), nullable=False),
    sa.Column('mitigation_status', sa.String(length=16), nullable=False),
    sa.Column('residual_severity', sa.String(length=16), nullable=True),
    sa.Column('residual_likelihood', sa.String(length=16), nullable=True),
    sa.Column('residual_level', sa.String(length=16), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('risk_id')
    )
    with op.batch_alter_table('risk_register', schema=None) as batch_op:
        batch_op.create_index('ix_risk_register_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_risk_register_risk_level', ['risk_level'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_register', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_register_risk_level')
        batch_op.drop_index('ix_risk_register_project_id')

    op.drop_table('risk_register')
    # ### end Alembic commands ###
