"""add explanation_requests table

Revision ID: bbf12c64c999
Revises: 2670783b7954
Create Date: 2026-05-09 19:33:21.427387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bbf12c64c999'
down_revision: Union[str, Sequence[str], None] = '2670783b7954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('explanation_requests',
    sa.Column('request_id', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=16), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('subject_reference', sa.String(length=128), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('decision_outcome', sa.Text(), nullable=False),
    sa.Column('request_received_date', sa.Date(), nullable=True),
    sa.Column('response_due_date', sa.Date(), nullable=True),
    sa.Column('response_sent_date', sa.Date(), nullable=True),
    sa.Column('factors_text', sa.Text(), nullable=False),
    sa.Column('alternative_paths', sa.Text(), nullable=False),
    sa.Column('human_review_offered', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('request_id')
    )
    with op.batch_alter_table('explanation_requests', schema=None) as batch_op:
        batch_op.create_index('ix_explanation_requests_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_explanation_requests_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('explanation_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_explanation_requests_status')
        batch_op.drop_index('ix_explanation_requests_project_id')

    op.drop_table('explanation_requests')
    # ### end Alembic commands ###
