"""add cybersecurity_plans table

Revision ID: f0879a4682d7
Revises: 3a6027e32dfc
Create Date: 2026-05-09 19:14:56.809000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f0879a4682d7'
down_revision: Union[str, Sequence[str], None] = '3a6027e32dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cybersecurity_plans',
    sa.Column('plan_id', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=16), nullable=False),
    sa.Column('threat_model_documented', sa.String(length=8), nullable=False),
    sa.Column('sbom_maintained', sa.String(length=8), nullable=False),
    sa.Column('pentest_performed', sa.String(length=8), nullable=False),
    sa.Column('data_poisoning_controls', sa.String(length=8), nullable=False),
    sa.Column('adversarial_input_controls', sa.String(length=8), nullable=False),
    sa.Column('privacy_attack_controls', sa.String(length=8), nullable=False),
    sa.Column('access_controls_documented', sa.String(length=8), nullable=False),
    sa.Column('incident_response_playbook', sa.String(length=8), nullable=False),
    sa.Column('pentest_last_date', sa.Date(), nullable=True),
    sa.Column('threat_model_notes', sa.Text(), nullable=False),
    sa.Column('open_findings', sa.Text(), nullable=False),
    sa.Column('mitigation_plan', sa.Text(), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('compliance_percent', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cybersecurity_plans')
    # ### end Alembic commands ###
