"""add sustainability_records table

Revision ID: f1125584fa19
Revises: f0879a4682d7
Create Date: 2026-05-09 19:18:35.593275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f1125584fa19'
down_revision: Union[str, Sequence[str], None] = 'f0879a4682d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sustainability_records',
    sa.Column('record_id', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=16), nullable=False),
    sa.Column('training_compute_kwh', sa.Float(), nullable=True),
    sa.Column('training_carbon_override_kg', sa.Float(), nullable=True),
    sa.Column('inference_kwh_per_1k_predictions', sa.Float(), nullable=True),
    sa.Column('monthly_predictions', sa.Integer(), nullable=True),
    sa.Column('deployment_region', sa.String(length=64), nullable=False),
    sa.Column('carbon_intensity_g_per_kwh', sa.Float(), nullable=False),
    sa.Column('assumptions', sa.Text(), nullable=False),
    sa.Column('data_source', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sustainability_records')
    # ### end Alembic commands ###
