"""baseline schema

Revision ID: f9bff52d1773
Revises: 
Create Date: 2026-05-09 10:38:31.243374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f9bff52d1773'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.String(length=16), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('folder_path', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('project_types',
    sa.Column('type_id', sa.String(length=16), nullable=False),
    sa.Column('type_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('standard_services', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=16), nullable=False),
    sa.Column('client_id', sa.String(length=16), nullable=False),
    sa.Column('project_type_id', sa.String(length=16), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('project_type', sa.String(length=255), nullable=False),
    sa.Column('project_type_description', sa.Text(), nullable=False),
    sa.Column('standard_services', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('folder_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['project_type_id'], ['project_types.type_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('systems',
    sa.Column('system_id', sa.String(length=16), nullable=False),
    sa.Column('client_id', sa.String(length=16), nullable=False),
    sa.Column('system_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('classification_date', sa.DateTime(), nullable=True),
    sa.Column('classification_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('system_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('systems')
    op.drop_table('projects')
    op.drop_table('project_types')
    op.drop_table('clients')
    # ### end Alembic commands ###
