"""
wavetest_app.cybersecurity — Art. 15(5) cybersecurity questionnaire
========================================================================

Eight yes / partial / no checkpoints scored 3/1/0 → percent. Same shape
as :mod:`wavetest_app.oversight`. This is the v0 of the cybersecurity
slice; a future iteration can wrap the Adversarial Robustness Toolbox
(`art`, already on the toolchain's environment) for active testing.
"""

from __future__ import annotations

from typing import Literal

Answer = Literal["yes", "partial", "no"]
ANSWERS: list[Answer] = ["yes", "partial", "no"]

# Field key → (display label, Art. 15 reference, short explanation)
CHECKPOINTS: list[tuple[str, str, str, str]] = [
    (
        "threat_model_documented",
        "Threat model is documented and current",
        "15(5)",
        "Has the team enumerated who would attack this system, why, "
        "and via which surfaces? STRIDE / LINDDUN style.",
    ),
    (
        "sbom_maintained",
        "Software Bill of Materials maintained + scanned for CVEs",
        "15(5)",
        "Including model dependencies (numpy, sklearn, transformers, …) "
        "and infrastructure libraries.",
    ),
    (
        "pentest_performed",
        "Penetration testing performed in the last 12 months",
        "15(5)",
        "External red-team review of the deployment, not just the model.",
    ),
    (
        "data_poisoning_controls",
        "Training-data integrity controls in place",
        "15(5)",
        "Data provenance tracking, anomaly detection on the training set, "
        "checks against label-flipping.",
    ),
    (
        "adversarial_input_controls",
        "Inference-time adversarial-input defences in place",
        "15(5)",
        "Input validation, anomaly detection, robustness training, "
        "or detection of evasion attacks (FGSM, PGD-style).",
    ),
    (
        "privacy_attack_controls",
        "Defences against membership-inference / model-inversion",
        "15(5)",
        "Differential privacy, output rate-limiting, distillation of the "
        "served model so it doesn't leak training-set membership.",
    ),
    (
        "access_controls_documented",
        "Access controls documented (deploy / retrain / serve)",
        "15(5)",
        "Who can push a new model? Who can read inference logs? RBAC + "
        "audit trail.",
    ),
    (
        "incident_response_playbook",
        "Incident-response playbook for compromise",
        "15(5)",
        "Documented runbook covering takedown, rollback, customer "
        "communication, and notified-body escalation.",
    ),
]

_ANSWER_SCORE = {"yes": 3, "partial": 1, "no": 0}


def compute_compliance_percent(answers: dict[str, str]) -> float:
    """Sum yes/partial/no scores ÷ (3 × n_checkpoints) × 100."""
    total = sum(
        _ANSWER_SCORE.get(answers.get(field, "no"), 0)
        for field, _, _, _ in CHECKPOINTS
    )
    max_total = 3 * len(CHECKPOINTS)
    return round(100.0 * total / max_total, 1) if max_total else 0.0


def status_color(compliance_percent: float) -> str:
    """Map a compliance percent to ok / warning / critical."""
    if compliance_percent >= 100:
        return "ok"
    if compliance_percent >= 50:
        return "warning"
    return "critical"


def to_markdown(plan: dict, *, project_label: str) -> str:
    """Render a plan dict as a Markdown deliverable."""
    lines = [
        f"# Cybersecurity Plan — {project_label}",
        "",
        "_EU AI Act Article 15(5) — resilience against alteration of use, "
        "outputs, or performance._",
        "",
        f"**Compliance**: {plan['compliance_percent']:.0f}%  ",
        f"**Last updated**: {plan['updated_at'].strftime('%Y-%m-%d %H:%M')}  ",
        f"**Last pentest**: "
        f"{plan['pentest_last_date'].isoformat() if plan.get('pentest_last_date') else '—'}  ",
        f"**Next review**: "
        f"{plan['next_review_date'].isoformat() if plan.get('next_review_date') else '—'}",
        "",
        "## Article 15(5) checkpoints",
        "",
        "| # | Requirement | Status |",
        "| --- | --- | --- |",
    ]
    for i, (field, label, _ref, _help) in enumerate(CHECKPOINTS, start=1):
        a = plan.get(field, "no")
        emoji = {"yes": "✅", "partial": "🟡", "no": "❌"}.get(a, "❌")
        lines.append(f"| {i} | {label} | {emoji} {a} |")

    lines += [
        "",
        "## Threat-model notes",
        "",
        plan.get("threat_model_notes") or "_Not yet documented._",
        "",
        "## Open findings",
        "",
        plan.get("open_findings") or "_None recorded._",
        "",
        "## Mitigation plan",
        "",
        plan.get("mitigation_plan") or "_None recorded._",
        "",
        "---",
        "",
        f"_Generated by wavetest-app · waveImpact GmbH._",
    ]
    return "\n".join(lines)
