"""
wavetest_app.incidents — Art. 73 serious-incident helpers
=============================================================

Article 73 requires providers of high-risk AI systems to report serious
incidents to the market-surveillance authority of the Member State
where the incident occurred. Reporting deadlines:

  * **2 days** — incidents resulting in death or serious harm to health
  * **15 days** — other serious incidents
  * **shorter** for safety-critical infrastructure

This module exposes the severity / status / deadline lookups and the
Markdown packet renderer for the notified body.
"""

from __future__ import annotations

from datetime import date
from typing import Optional

# Severity → (display label, deadline in days, status colour)
SEVERITIES: dict[str, tuple[str, int, str]] = {
    "death_or_serious_health": ("Death or serious health harm",          2,  "critical"),
    "fundamental_rights":      ("Fundamental rights infringement",       15, "critical"),
    "property_damage":         ("Property or environmental damage",      15, "warning"),
    "near_miss":               ("Near-miss / no harm caused",            15, "info"),
}

STATUSES: list[str] = [
    "open", "investigating", "corrective_actions", "closed",
]
STATUS_COLOR = {
    "open":               "critical",
    "investigating":      "warning",
    "corrective_actions": "warning",
    "closed":             "ok",
}


def deadline_days(severity: str) -> int:
    """Reporting deadline (days) per severity. Defaults to 15 if unknown."""
    return SEVERITIES.get(severity, ("", 15, "info"))[1]


def days_remaining(
    severity: str,
    date_detected: Optional[date],
    today: Optional[date] = None,
) -> Optional[int]:
    """Days until the Art. 73 reporting deadline (negative = overdue).

    Returns None if no detection date is recorded.
    """
    if date_detected is None:
        return None
    today = today or date.today()
    elapsed = (today - date_detected).days
    return deadline_days(severity) - elapsed


def deadline_color(
    severity: str,
    date_detected: Optional[date],
    date_reported: Optional[date],
) -> str:
    """ok / warning / critical for the Streamlit pill."""
    if date_reported is not None:
        return "ok"  # already reported
    rem = days_remaining(severity, date_detected)
    if rem is None:
        return "info"
    if rem < 0:
        return "critical"  # overdue
    if rem <= 3:
        return "warning"
    return "ok"


def to_markdown(incident: dict) -> str:
    """Render an incident as a Markdown packet for the notified body."""
    sev_label, deadline, _ = SEVERITIES.get(
        incident.get("severity", "near_miss"),
        (incident.get("severity", "?"), 15, "info"),
    )

    def _fmt_date(d):
        return d.isoformat() if d else "_not recorded_"

    lines = [
        f"# Incident Report — {incident['incident_id']}",
        "",
        "_Filed under EU AI Act Article 73 — serious-incident reporting._",
        "",
        f"**Title**: {incident.get('title', '—')}  ",
        f"**Project**: `{incident.get('project_id') or '—'}` "
        f"({incident.get('project_name', '—')})  ",
        f"**Client**: {incident.get('client_name') or '—'}  ",
        f"**Severity**: {sev_label} (deadline: {deadline} days)  ",
        f"**Status**: {incident.get('status', '—')}",
        "",
        "## Timeline",
        "",
        "| Event | Date |",
        "| --- | --- |",
        f"| Occurred | {_fmt_date(incident.get('date_occurred'))} |",
        f"| Detected | {_fmt_date(incident.get('date_detected'))} |",
        f"| Reported to authority | {_fmt_date(incident.get('date_reported'))} |",
        "",
        "## Affected persons",
        "",
        f"{incident.get('affected_persons', 0)}",
        "",
        "## Summary",
        "",
        incident.get("summary") or "_Not provided._",
        "",
        "## Detailed description",
        "",
        incident.get("description") or "_Not provided._",
        "",
        "## Root cause",
        "",
        incident.get("root_cause") or "_Investigation pending._",
        "",
        "## Corrective action",
        "",
        incident.get("corrective_action") or "_Not yet defined._",
        "",
        "## Authority notification",
        "",
        f"- **Notified**: {'Yes' if incident.get('authority_notified') else 'No'}",
        f"- **Authority**: {incident.get('authority_name') or '—'}",
        f"- **Reference**: {incident.get('authority_reference') or '—'}",
        "",
        "## Notes",
        "",
        incident.get("notes") or "_None._",
        "",
        "---",
        "",
        f"_Generated by wavetest-app · waveImpact GmbH._",
    ]
    return "\n".join(lines)
