"""
wavetest_app.oversight — Art. 14 human-oversight scoring helpers
====================================================================

Six yes / partial / no checkpoints map to Art. 14.4 (a)–(e). Each yes
scores 3, partial 1, no 0 — total /18 → percentage. Threshold for
"compliant" is 100% (every checkpoint at least *partial* is the legal
floor; full yes is the spirit of the article).
"""

from __future__ import annotations

from typing import Literal

Answer = Literal["yes", "partial", "no"]
ANSWERS: list[Answer] = ["yes", "partial", "no"]

# Checkpoint identifier → (display label, Art. 14.4 sub-clause)
CHECKPOINTS: list[tuple[str, str, str]] = [
    (
        "has_documentation",
        "Operators have documentation covering capabilities and limitations",
        "14.4(a)",
    ),
    (
        "automation_bias_training",
        "Operators are trained to recognise automation bias",
        "14.4(b)",
    ),
    (
        "outputs_include_uncertainty",
        "Outputs include confidence / uncertainty information",
        "14.4(c)",
    ),
    (
        "override_mechanism",
        "Operators can disregard or reverse system outputs",
        "14.4(d)",
    ),
    (
        "override_logged",
        "Overrides are logged and traceable to a specific operator",
        "14.4(d)",
    ),
    (
        "stop_mechanism",
        "Stop / interrupt mechanism exists and is documented",
        "14.4(e)",
    ),
]

_ANSWER_SCORE = {"yes": 3, "partial": 1, "no": 0}


def compute_compliance_percent(answers: dict[str, str]) -> float:
    """Sum of yes/partial/no scores ÷ 18 × 100. Range [0.0, 100.0]."""
    total = sum(
        _ANSWER_SCORE.get(answers.get(field, "no"), 0)
        for field, _, _ in CHECKPOINTS
    )
    max_total = 3 * len(CHECKPOINTS)
    return round(100.0 * total / max_total, 1) if max_total else 0.0


def status_color(compliance_percent: float) -> str:
    """Map a compliance percent to the app's ok/warning/critical palette."""
    if compliance_percent >= 100:
        return "ok"
    if compliance_percent >= 50:
        return "warning"
    return "critical"


def to_markdown(plan: dict, *, project_label: str) -> str:
    """Render a plan dict as a Markdown deliverable for the customer."""
    lines = [
        f"# Human Oversight Plan — {project_label}",
        "",
        "_EU AI Act Article 14 — designed to support effective human oversight._",
        "",
        f"**Compliance**: {plan['compliance_percent']:.0f}%  ",
        f"**Last updated**: {plan['updated_at'].strftime('%Y-%m-%d %H:%M')}  ",
        f"**Next review**: "
        f"{plan['next_review_date'].isoformat() if plan.get('next_review_date') else '—'}",
        "",
        "## Operator profile",
        "",
        plan.get("operator_profile") or "_Not yet documented._",
        "",
        "## Article 14.4 checkpoints",
        "",
        "| # | Requirement | Sub-clause | Status |",
        "| --- | --- | --- | --- |",
    ]
    for i, (field, label, ref) in enumerate(CHECKPOINTS, start=1):
        a = plan.get(field, "no")
        emoji = {"yes": "✅", "partial": "🟡", "no": "❌"}.get(a, "❌")
        lines.append(f"| {i} | {label} | Art. {ref} | {emoji} {a} |")

    lines += [
        "",
        "## Open gaps",
        "",
        plan.get("gaps") or "_None recorded._",
        "",
        "## Mitigation plan",
        "",
        plan.get("mitigation_plan") or "_None recorded._",
        "",
        "---",
        "",
        f"_Generated by wavetest-app · waveImpact GmbH._",
    ]
    return "\n".join(lines)
